#!/bin/sh
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev python-pip
# wget http://www.python.org/ftp/python/2.7.8/Python-2.7.8.tar.xzmake

sudo pip install virtualenv
virtualenv venv

